#goal definition
geometry_msgs/Twist result_velocity
---
#result definition
geometry_msgs/Twist result_velocity
---
float32 remaining



#goal definition
geometry_msgs/Point target
float32 speed
---
#result definition
builtin_interfaces/Duration total_elapsed_time
---
float32 distance_traveled
